### ISSUE TITLE
Create new class fails

### ISSUE THREAD

**Issue by thegreatmichael** [VT-CHCI/CritiSearch.org#24]
It's still using the old db connection, it should instead utilize sequelize

**Comment by thegreatmichael** [comment]
see `makeName` and `bulkCreateParticipants`  https://github.com/VT-CHCI/Thought-Swap/blob/develop/server.js#L80 in ThoughtSwap

**Comment by sarang87** [comment]
Fixed in commits
1>b3a1f5b2c56e693ef50fe27aac968c2d4c3a4235
2> af70cf44d33452679de158c4d8c6b586146e6119
