### ISSUE TITLE
Related Link and Cited URL to open a new critiseacrh tab instead of a scholar tab

### ISSUE THREAD

**Issue by sarang87** [VT-CHCI/CritiSearch.org#33]

**Comment by thegreatmichael** [comment]
for related link, we should parse out the value of URL param `q` (looks something like `related:UpmKQyIl3CYJ:scholar.google.com`) and link to `/#/scholar/<that query>`, i.e. `/#/scholar/related:UpmKQyIl3CYJ:scholar.google.com`
for citedby link, we should parse out the value for URL param `cites` and throw an ampersand on the front so the link should be like: `/#/scholar/&cites=2800153897409878354`

**Comment by thegreatmichael** [comment]
@sarang87 fixed this in acb81a16bf632cad1fd3b8916fccfb8e044af50c
